#!/bin/sh

: ${REPO_ROOT:=/data/mail}
: ${SNITCH_URL:=}

set -eu

warn () {
  echo "WARNING: ${@}" >&2
}

check_git_clean () {
  BRANCH=$(git symbolic-ref HEAD | sed 's|^refs/heads/||')

  if [ -f lock ]; then
    warn "'lock' file exists"
    return 1
  elif [ "$BRANCH" != "master" ]; then
    warn "on non-master branch"
    return 1
  elif ! git diff --quiet --ignore-submodules --no-ext-diff; then
    warn "uncommitted local changes"
    return 1
  # else
  #   git fetch -q origin
  #   if ! git merge --ff-only origin/master >/dev/null 2>&1; then
  #     warn "unpushed local commits"
  #     return 1
  #   else
  #     return 0
  #   fi
  fi
}

cd "$REPO_ROOT"

if ! check_git_clean; then
  warn "git repository not in clean state, aborting."
  exit 1
fi

offlineimap -o

git add -A .
if ! git diff --cached --quiet --ignore-submodules --no-ext-diff; then
  git commit -q \
             -m "Automatic commit by $(basename "$0")" \
             --author "Gitmail <gitmail@$(hostname -f)>"
  # git push -q origin master
fi

if [ -n "$SNITCH_URL" ]; then
  curl -sSL "$SNITCH_URL" >/dev/null 2>&1
fi
